spring:
  jpa:
    # transmitted query confirmed
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # run data.sql after table founded
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test_id
            client-secret: test_secret
            scope:
              - email
              - profile

jwt:
  issuer: yunanii@ourbox.co.kr
  secret_key: test_key
